// Code generated by Slice Machine. DO NOT EDIT.

import Bento from './Bento/index.svelte';
import CallToAction from './CallToAction/index.svelte';
import CaseStudies from './CaseStudies/index.svelte';
import Hero from './Hero/index.svelte';
import Integrations from './Integrations/index.svelte';
import RichText from './RichText/index.svelte';
import Showcase from './Showcase/index.svelte';

export const components = {
	bento: Bento,
	call_to_action: CallToAction,
	case_studies: CaseStudies,
	hero: Hero,
	integrations: Integrations,
	rich_text: RichText,
	showcase: Showcase
};
